# Updates the license cache, then checks that all dependencies have licenses specified in .licensed.yml
# Uses https://github.com/jonabc/licensed-ci

name: Check and Update Licenses Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --production
      - uses: jonabc/setup-licensed@v1
        with:
          version: 3.x
      - id: licensed
        uses: jonabc/licensed-ci@v1
        with:
          workflow: branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
